---
date: 2025-05-09
hora: 18:08
tags:
---




# Coisas
- [ ] Academia
- [ ] Tomar rem√©dio
- [ ] Tomar Creatina

# Erro
2025-05-09 13:43:00.105896: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-09 13:43:03.310660: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
D:\bot binance\Datasets\Modelo C\modeloC.1.py:53: DtypeWarning: Columns (3,5,8,9,11,13,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path, usecols=feature_cols+['symbol_id','target'])
Traceback (most recent call last):
  File "D:\bot binance\Datasets\Modelo C\modeloC.1.py", line 77, in <module>
    train_ds = make_windowed_ds(ALL_CSV, feature_cols, scaler, WINDOW_SIZE, STRIDE, BATCH_SIZE, shuffle=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bot binance\Datasets\Modelo C\modeloC.1.py", line 53, in make_windowed_ds
    df = pd.read_csv(csv_path, usecols=feature_cols+['symbol_id','target'])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1968, in read
    df = DataFrame(
         ^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\construction.py", line 152, in arrays_to_mgr
    return create_block_manager_from_column_arrays(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\managers.py", line 2139, in create_block_manager_from_column_arrays
    blocks = _form_blocks(arrays, consolidate, refs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\managers.py", line 2212, in _form_blocks
    values, placement = _stack_arrays(list(tup_block), dtype)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\managers.py", line 2252, in _stack_arrays
    stacked = np.empty(shape, dtype=dtype)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.65 GiB for an array with shape (34, 10471991) and data type object
